imports:
    # A. monorepo location
    # see https://symfony.com/blog/new-in-symfony-4-4-dependency-injection-improvements-part-1#ignore-errors-when-importing-files
    - { resource: '../../../vendor/symplify/easy-hydrator/config/config.yaml', ignore_errors: 'not_found' }
    # B. composer dependency
    - { resource: '../../../../vendor/symplify/easy-hydrator/config/config.yaml', ignore_errors: 'not_found' }

parameters:
    route_usage_exclude_routes: []

services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: true

    Migrify\SymfonyRouteUsage\:
        resource: '../src'
        exclude:
            - '../src/Entity/*'
            - '../src/ValueObject/*'

    Symplify\PackageBuilder\Console\Style\SymfonyStyleFactory: null

    Symfony\Component\Console\Style\SymfonyStyle:
        factory: ['@Symplify\PackageBuilder\Console\Style\SymfonyStyleFactory', 'create']
